channels:
  targets:
  - [nomr, main]
travis:
  secure:
    BINSTAR_TOKEN: W5JfaPf8pmDdq64dFsb5UEQglVMyc/vJhvFvFDiimwtfOVuIl2RNoGR3sbaj0PAIghWVbnvulCGFCpL9LFYi5I0ZmHm9nOuZvgcCMBFiK5oePfWm8wgkU4wbRPZz4pOxlXzYFOAFBUGvC0pANxbfSDaFtscZpOGsNhU+x/3XZiKLsXyPJNvkCmNnw9VRr1M+A1fYdCLZZhJ2qV4Mjwc1AHlkyGp++Lbv+5NSN2fa0rK+XzHFX32bblaCCdDHTa3vLaf/hXr6GPr6EtfP3j7qngk+Ydi6XtfEWc6kBMS2E1e0CMvJ8BrC/pfGJd1FwsnOOvOlCCQ8InopLJIVr/DM37GFWzZWiATlTlhbLZv5cxuFcTOYmBNPQYjR7BPB27Emik0NNHFPQDbKC2D3gEFbV6OX57OuFunnmaXmGjHvLlhxy3tZ1qBfob8ibqREKzyBmCYAgZNmJ8joJUazvIovHO6ANwjUXwhiQRHBYIVflyKKJtDnEGDIyNo0EFJoqzHVNLoDW0/FSXirUL9BAENMj6bRyc4o0TOkPjQhd+1NdmL+yYZCuNhMXS4DSu+VwGe173YgyrZ+B26yF4kwRCam96lRxPv/dWugyYtGvA983UnTazao22hD2AMlGzbiZk1C9c+R8BdLnGxBbA5yjxDNnq6HIe5Mjr+FKWT4gU0157c=
appveyor:
  secure:
    BINSTAR_TOKEN: jmfNaxlxF2AAuLMeaUYsm/Jqv7BxlRYmp6gm16lU2g/T3ov0fu8vNHq1jtF2Vwjy
