channels:
  targets:
  - [nomr, main]
travis:
  secure:
    BINSTAR_TOKEN: N5gBv7LK4vyRxF3YhMXCt44NEuXfpac9PEvtbbSsMS11jtq4UDh54MAWJLfmva2Am+L7SU3IcyGe30bKcEYWDmDBfM8NYCqiVqluE972U7gjv1M0uSLglAMe93hnTeWq1/bWWHY9lm8XLJAVxLi98Fkey3rYbBiVmEf+8LmD0/yGu9xrjfZEW+HwPhvIZjMEpP53rBcopvsZYHbEylBfC9x8X6V3IUqrNi3YxBgcby7jvsZTwzp46ey9EJQha8e7Hyhti2yNVCqih+yVbW66rJomGrmSYKYYYb6ep/9sVI3UxrIMgdTfLcSUbOznqC3DIzTeuhvrHIPnRcs6nyP+0g325lt2BZS8gphDXI23zkaPZX3hNICQl6HJ20ud/muHCn2oRsCZSMmD71Bw32K8hYeF8Ry3a8vww8DDk+8u8IVKZ2BjTFKaIHs0sY9zb2O2v4sl1BVunMGavXJydlmfa5aoZT8O6pYp1VWNAFWicTdjbZcE/MhgU4emLsD55syhsTNL2Bxfwu7AE3WfFntZyvtsdmQweABV024BlynYksX+/HIWbK0QGEz3HjkF4TNhkXPQ5KdKhZzahmGnk7fevYvYA+6nxt9KFOQCZpJ6CSp9xzVPPb6+WMq/VCbsmEZ9hJF07LrocC++eOPwJULJuyVvdnbV44TX0fWsVr7FTas=
appveyor:
  secure:
    BINSTAR_TOKEN: jmfNaxlxF2AAuLMeaUYsm/Jqv7BxlRYmp6gm16lU2g/T3ov0fu8vNHq1jtF2Vwjy
