channels:
  targets:
  - [nomr, condavisor]
travis:
  secure:
    BINSTAR_TOKEN: Tfb6Xw8tHemPivplpY4RIpf9azZaUHRb32QL53T6btDbJCa3O+/mMHH6O76OBzICCxE8aVOAzD9vam2lSj7d58me5upu/4lUsV3XbHePsk1/xYOlJuiA5oiVfRwFIA9pY7/3oxUKZxNcm6QgNyi9mHYsmWOx22zoto6Gvhm9DOkW0A8vUZ/VipxOyeAY2R6MqSgxWT5rlGBsNDqDrhTHldUTW42sBJeFnDEAFyOPre0AeEN7difofJX7aF30Z3IMDztMp/RCSa2s7U+fIV6v8/UMqwb5i0FGVjz0nR0CVxlnqgYplxdoMmGN/9Lv0YYfOe9iHM5rb1koMHYgh7siuLuRrdLFQbriYGtdVIXbv7CAWkpwPhuhfmBNGyWdh2rC+MLlHXorUzzEDzkct4CR+ViHQ4Xq0yLtWxh66yvbUavm3XNNAQZk9UFUbyeCtS4X9VXrrllwXY7aBRP3KdYEC+YP3TrV+g4UD5q7ehSBm60FUEP2wWQUYla856GvtWiPsRDL9W8EyxwkcsQHGQEadBUS9fbiigMvpLjZi5x2pCbsoI+kmSdTUSHJ+j6hi5QG+iFtmvQ3hXYpxBJKW+/QIEPkl2CH1T4CxXu0PqJab6m36Vs4ZK+N9nq4ZsGHcX3KOfQvDLQoHlPMzww0HA88YpAVpHuKcC6+8rSelPSusr4=
appveyor:
  secure:
    BINSTAR_TOKEN: jmfNaxlxF2AAuLMeaUYsm/Jqv7BxlRYmp6gm16lU2g/T3ov0fu8vNHq1jtF2Vwjy
