channels:
  targets:
  - [nomr, main]
travis:
  secure:
    BINSTAR_TOKEN: xjQHUoOUZVDQY5p7wEKYeMH2XlmTewQU8a/4XwhbZ+YCAWQrBOrIANskvO5SUjA+8qand0TQWMW4CgUKDAnAIAGCb46VZXPlovak6kgyg4kB+pGnT9f1oOOP/5U5pvNSxNIFaIX1ySDb8t7hj4HphaIMKPAdV0RJk5DOYDp/yIqjjac7LNkhbU8qbpeLPrJXtAixKp6K1VIcyZ+MrNO6qNOPWXEH/eSh1lARPny+1kQ9Zwd0KrHW4XeZd+r42Ihq95WW4OjDPnLM54j4CawYGT8enw9BBS0TmV27Eqfr9IY6vRY9LjlxUCkwsJjo5ZG5K8V3rhqLQcHXx0sdCkIDlad9I+Om3WmOFFYEPFa3C54Gf03N6az46e4STk9tMJt+dhuXe83G/7QWc2ZbH4E4DjRBiNEjV/2DIhu8YJ/TpLPGNvvkWCyINIgBrDHbxr8MiWjK0TAN8BCScnsobihvGqPez5fBjisbYg4jwH4BYbZTymPjJbahW+g8xbsNKTm4WGWj5bx3B1CJH2kQMZpJCy5Es+vtg7AM0x3OVvKpzp53tfCxdJozTGHDHkcoS6xtqQ4XLgL1yzffpNHv8yWeBdbxGb3sa6X/S+bFFE178NG1kZDO5/E7DwBdLH4pIkM0GOJKUlHdjQt9pPTAXsPKBaC8IlcNfkgPfdncwfsMDlA=
appveyor:
  secure:
    BINSTAR_TOKEN: jmfNaxlxF2AAuLMeaUYsm/Jqv7BxlRYmp6gm16lU2g/T3ov0fu8vNHq1jtF2Vwjy
